name: check branch name
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: check branch name
        run: chmod +x .github/shell/branch-name.sh && .github/shell/branch-name.sh ${GITHUB_REF#refs/heads/}
